# Generated by Django 6.0.2 on 2026-02-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, unique=True)),
                ('level', models.IntegerField()),
                ('montlhy_leave_accrual', models.FloatField(default=1.5)),
            ],
        ),
    ]
