"""add extra_data to requests

Revision ID: 316c216908ff
Revises: f89b4ff33f5d
Create Date: 2026-03-09 12:00:17.323886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316c216908ff'
down_revision: Union[str, Sequence[str], None] = 'f89b4ff33f5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_request_step_order', 'approval_steps', ['request_type_id', 'step_order'])
    op.add_column('requests', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requests', 'extra_data')
    op.drop_constraint('uix_request_step_order', 'approval_steps', type_='unique')
    # ### end Alembic commands ###
