"""create job_title table

Revision ID: 8c0e08fc618c
Revises: 545794f770e8
Create Date: 2026-03-01 14:29:28.080483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0e08fc618c'
down_revision: Union[str, Sequence[str], None] = '545794f770e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('TEAM', 'DEPARTMENT', 'GLOBAL', name='positionscope'), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('monthly_leave_accrual', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_job_titles_id'), 'job_titles', ['id'], unique=False)
    op.drop_index(op.f('ix_job_titel_id'), table_name='job_titel')
    op.drop_table('job_titel')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titel',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('scope', sa.VARCHAR(length=10), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('monthly_leave_accrual', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_job_titel_id'), 'job_titel', ['id'], unique=False)
    op.drop_index(op.f('ix_job_titles_id'), table_name='job_titles')
    op.drop_table('job_titles')
    # ### end Alembic commands ###
