"""create job_title table

Revision ID: ab07f4a44c4a
Revises: bc5f729eb630
Create Date: 2026-03-01 13:37:03.609229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab07f4a44c4a'
down_revision: Union[str, Sequence[str], None] = 'bc5f729eb630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_titel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('scope', sa.Enum('TEAM', 'DEPARTMENT', 'GLOBAL', name='positionscope'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('monthly_leave_accrual', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_job_titel_id'), 'job_titel', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_titel_id'), table_name='job_titel')
    op.drop_table('job_titel')
    # ### end Alembic commands ###
