# Generated by Django 6.0.2 on 2026-02-22 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0002_approvalworkflow'),
        ('users', '0005_leaveadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.PositiveIntegerField()),
                ('use_hierarchy', models.BooleanField(default=False)),
                ('required_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='users.jobposition')),
                ('restricted_departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='users.departement')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='requests_engine.approvalworkflow')),
            ],
            options={
                'ordering': ['step_order'],
                'unique_together': {('workflow', 'step_order')},
            },
        ),
    ]
