# Generated by Django 6.0.2 on 2026-02-22 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0003_approvalstep'),
        ('users', '0005_leaveadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('cuurent_step', models.PositiveIntegerField(default=1)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='requests_engine.requesttype')),
                ('submetted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='users.userprofile')),
            ],
        ),
    ]
