# Generated by Django 6.0.2 on 2026-02-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0005_approvalhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='cuurent_step',
            new_name='current_step',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='submetted_by',
            new_name='submitted_by',
        ),
    ]
