# Generated by Django 6.0.2 on 2026-02-22 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0007_request_description_request_extra_data'),
        ('users', '0005_leaveadjustment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approvalstep',
            old_name='use_hierarchy',
            new_name='apply_hierarchy',
        ),
        migrations.RemoveField(
            model_name='approvalstep',
            name='restricted_departement',
        ),
        migrations.AddField(
            model_name='approvalstep',
            name='restricted_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.departement'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='required_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.jobposition'),
        ),
    ]
