# Generated by Django 6.0.2 on 2026-02-22 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflow', to='requests_engine.requesttype')),
            ],
        ),
    ]
