# Generated by Django 6.0.2 on 2026-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0006_rename_cuurent_step_request_current_step_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='extra_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
