# Generated by Django 6.0.2 on 2026-02-24 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_engine', '0008_rename_use_hierarchy_approvalstep_apply_hierarchy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalworkflow',
            name='request_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='requests_engine.requesttype'),
        ),
    ]
